### PR TITLE
chore(keys): add age key for puiterwijk

### PR DESCRIPTION
**Pull request by puiterwijk**
Fixes: #107
Signed-off-by: Patrick Uiterwijk <patrick@profian.com>

### CODE REVIEW

**Review by rvolosatovs — COMMENTED** [review]
It looks good to me, but last time I tried something like this, the result was not what I have expected, in particular I was only able to decrypt the secret when *both* keys were present.
That may be a sops oddity, but it looks like `shamir_threshold` is at minimum 2
Refs https://github.com/mozilla/sops/issues/878 I suppose.

What I did was try to encrypt a secret both for my GPG key and the host SSH (age) key. It's unlikely, but possible that the issue was caused by my trying to use different types of keys. It could be that it does not occur when only GPG or age keys are used, but I doubt that.

Any ideas on how to proceed here?
Can you verify that creating a secret in `ca/` does indeed produce a secret you can read?

**Comment by rvolosatovs** [comment]
```
$ echo 'test' > ca/test.txt                                    
$ sops -i -e ca/test.txt                                   
[PGP]	WARN[0000] Deprecation Warning: GPG key fetching from a keyserver within sops will be removed in a future version of sops. See https://github.com/mozilla/sops/issues/727 for more information. 
$ sops ca/test.txt 
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  age1jsyhycrf872ksv88qk8lfp3whtjxrr4r3mk0m6fa49evev3pmywsf3aa2r: FAILED
    - | failed to open file: open
      | /home/rvolosatovs/.config/sops/age/keys.txt: no such file or
      | directory

Group 1: SUCCESS

Recovery failed because the file was encrypted with a Shamir threshold of
2, but only 1 part(s) were successfully recovered, one for each successful
key group. In order for SOPS to recover the file, at least 2 groups have to
be successful. In order for a group to be successful, decryption has to
succeed with any of the keys in that key group.
```

**Comment by rvolosatovs** [comment]
I'll try to add my ed25519 (age) key to see if that fixes the issue

**Comment by puiterwijk** [comment]
@rvolosatovs see my latest commit. With this, I am able to create and decrypt things (it basically adds both our keys as a third and fourth group).

**Review by rvolosatovs — APPROVED** [review]
Nice! Works for me locally as well

**Pull request merged**
